// <auto-generated />
using System;
using EFCoreInheritance.TablePerHierarchy;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCoreInheritance.TablePerHierarchy.Migrations
{
    [DbContext(typeof(PolicyTemplateDbContext))]
    [Migration("20201126015156_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EFCoreInheritance.Domain.Entities.OrganizationPolicyTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PolicyTemplateHierarchy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PolicyTemplate");

                    b.HasDiscriminator<int>("PolicyTemplateHierarchy").HasValue(1);
                });

            modelBuilder.Entity("EFCoreInheritance.Domain.Entities.RegionPolicyTemplate", b =>
                {
                    b.HasBaseType("EFCoreInheritance.Domain.Entities.OrganizationPolicyTemplate");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("EFCoreInheritance.Domain.Entities.CountryPolicyTemplate", b =>
                {
                    b.HasBaseType("EFCoreInheritance.Domain.Entities.RegionPolicyTemplate");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(3);
                });
#pragma warning restore 612, 618
        }
    }
}
